# Generated by Django 4.1 on 2024-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('translated_transcription', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
