# Generated by Django 4.1 on 2024-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai_video_service_django_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranslation',
            name='s3_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
