# Generated by Django 4.1 on 2024-11-13 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('samurai_video_service_django_api', '0002_videotranslation_s3_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranslation',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='videotranslation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Received'), (1, 'Error Occurred'), (2, 'In Progress'), (3, 'Ready')], default=0),
        ),
    ]
