# Generated by Django 4.1 on 2024-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai_video_service_django_api', '0003_videotranslation_request_id_videotranslation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranslation',
            name='start_minute',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='videotranslation',
            name='user_id',
            field=models.FloatField(),
        ),
    ]
