# Generated by Django 4.1 on 2024-11-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai_video_service_django_api', '0004_alter_videotranslation_start_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranslation',
            name='end_minute',
            field=models.FloatField(),
        ),
    ]
