# Generated by Django 4.1 on 2024-11-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samurai_video_service_django_api', '0005_alter_videotranslation_end_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranslation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Received'), (1, 'Error Occurred'), (2, 'In Progress'), (3, 'Ready'), (4, 'Delivered')], default=0),
        ),
    ]
