# Generated by Django 4.1 on 2024-11-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samurai_video_service_django_api", "0006_alter_videotranslation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videotranslation",
            name="request_id",
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="videotranslation",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
